# Global bot attributes
bot:
  prefix: '!'
  admins: [368671236370464769]

# Consistent styling
style:
  exception: 0x880808
  sunshine: 0xFFDF00
  deepblue: 0x00aced
# Links and prompts
props:
  character: https://cdn.discordapp.com/emojis/818820065834303488.png?v=1
  help_board: https://cdn.discordapp.com/attachments/818028373749268502/818822573751795752/helpingboard.png
  help_desc: 'Pill''s help index menu. Use the following commands with the prefix **`p!`** to get further information about each commands. [<Hover me!>](https://google.com "Hover over hyperlinks to find out details about the system")'