# The asthetic configuration for the bot
asthetics:
    mainColor: 0xFFDF00
    errorColor: 0x880808
    verifierColor: 0x00aced

# The directory layout for importing purposes d < e < f
dirLayout:
    d: bot
    e: auth, fun, moderation, resources, utilities
    f: fun_cosmetics, __pycache__

directories:
    assets: bot/resources/
    prompts: bot/resources/prompts.yaml